spring:
    flink:
        examples:
            wordcount:
                nc-host: 192.168.56.2
                nc-port: 8888
            source-kafka:
                bootstrap-servers: 192.168.56.2:9092
            sink-kafka:
                bootstrap-servers: 192.168.56.2:9092
            slink-redis:
                host: 127.0.0.1
                port: 6379