#SpringBoot自动配置开启debug模式
debug: false

#应用日志配置
logging:
    config: classpath:log4j2-spring.xml
    file: 
        name: ${spring.application.name}
        path: /var/log/${spring.application.name}

#Spring上下文初始化程序
context:
    initializer:
        classes: com.penglecode.flink.examples.common.initializer.DefaultSpringAppPreInitializer

#SpringBoot应用的名称
spring:
    application:
        name: flink-examples-basic
    #配置文件激活配置
    profiles:
        active: dev
    #Spring国际化配置
    messages:
        basename: config/i18n/messages
        cache-duration: -1
        encoding: UTF-8

#Feign客户端配置
feign:
    okhttp:
        enabled: true
    circuitbreaker:
        enabled: true
    client:
        config:
            default:
                connect-timeout: 6000
                read-timeout: 60000
                logger-level: full
        #openapi的URL
        openapi:
            url: https://api.apiopen.top

#Hystrix(熔断|降级)配置
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        #默认的熔断超时时间,默认1000毫秒,需要设大点否则很容易触发熔断
                        timeoutInMilliseconds: 15000